apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventrouter
  namespace: demo-system
  labels:
    eventrouter: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      eventrouter: "true"
  template:
    metadata:
      labels:
        eventrouter: "true"
    spec:
      serviceAccountName: eventrouter
      volumes:
        - emptyDir: {}
          name: tmp-dir
      containers:
      - name: eventrouter
        image: kind.local/eventrouter:latest
        imagePullPolicy: Never
        args:
          - --insecure=true
          - --debug=true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
          - mountPath: /tmp
            name: tmp-dir
    