kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eventrouter
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "get"
  - "list"
- nonResourceURLs:
  - "*"
  verbs:
  - "get"
  - "list"
