apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventrouter 
  namespace: krateo-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventrouter 
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list", "patch"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]
- nonResourceURLs: ["*"]
  verbs:  ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventrouter 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventrouter
subjects:
- kind: ServiceAccount
  name: eventrouter
  namespace: krateo-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventrouter
  namespace: krateo-system
  labels:
    app: eventrouter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventrouter
  template:
    metadata:
      labels:
        app: eventrouter
        tier: krateo-addons
    spec:
      serviceAccount: eventrouter
      containers:
        - name: krateo-eventrouter
          image: ghcr.io/krateoplatformops/eventrouter:v0.1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: EVENT_SERVICE_URL
              value: http://log-service-service.krateo-system.svc
            - name: EVENT_ROUTER_DEBUG
              value: "false"
